"""Build isolated molecules via several construction methods.

Supports four construction pathways:

* **ASE database** — common small molecules (H2O, CO2, C60, …) via
  ``ase.build.molecule``.
* **SMILES** — organic molecules with 3-D coordinates generated by RDKit.
* **Organometallic** — hand-built metal–organic compounds (e.g. ferrocene).
* **Endohedral** — a guest molecule encapsulated inside a carbon cage
  (C60 or custom Fibonacci-sphere cages).

CLI usage::

    mmkit operate molecule from_ase H2O -o water.extxyz
    mmkit operate molecule from_smiles "CCO" -o ethanol.extxyz
    mmkit operate molecule organometallic --type ferrocene -o ferrocene.extxyz
    mmkit operate molecule endohedral --cage C60 --guest H2O -o endo.extxyz
"""

from __future__ import annotations

from typing import Optional

import numpy as np
from ase import Atoms
from ase.build import molecule as ase_molecule

from mmkit.core.structure import Structure
from mmkit.core.tool import Operation


# ---------------------------------------------------------------------------
# Builder classes
# ---------------------------------------------------------------------------

class ASEMoleculeBuilder(Operation):
    """Build a molecule from ASE's built-in molecule database.

    ASE ships with a collection of pre-defined molecules with experimental
    geometries (H2O, CO2, CH4, C6H6, C60, etc.).

    Example
    -------
    >>> ASEMoleculeBuilder().apply(name="H2O")
    """

    def apply(self, *, name: str) -> Structure:
        """Build a molecule by name from the ASE database.

        Parameters
        ----------
        name
            Molecule name recognised by ``ase.build.molecule``
            (e.g. ``"H2O"``, ``"CO2"``, ``"C60"``, ``"C6H6"``).
        """
        atoms = ase_molecule(name)
        atoms.pbc = False
        return Structure.from_ase_atoms(atoms)


class SMILESMoleculeBuilder(Operation):
    """Build a molecule from a SMILES string using RDKit.

    RDKit generates 3-D coordinates via conformer embedding and optionally
    optimises the geometry with the MMFF force field.

    Example
    -------
    >>> SMILESMoleculeBuilder().apply(smiles="CCO")          # ethanol
    >>> SMILESMoleculeBuilder().apply(smiles="c1ccccc1")     # benzene
    """

    def apply(
        self,
        *,
        smiles: str,
        optimize: bool = True,
        vacuum: float = 5.0,
    ) -> Structure:
        """Generate a 3-D molecular structure from a SMILES string.

        Parameters
        ----------
        smiles
            SMILES notation of the molecule.
        optimize
            Run MMFF force-field optimisation after embedding.
        vacuum
            Vacuum padding (Å) added around the molecule.
        """
        from rdkit import Chem
        from rdkit.Chem import AllChem

        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            # Provide helpful hints for common SMILES errors
            hints = []
            if any(c.islower() and c.isalpha() for c in smiles):
                # Check if lowercase atoms might be outside rings
                hints.append(
                    "Lowercase atoms (c, n, o) denote aromatic atoms and must be in a ring. "
                    "Try uppercase (C, N, O) for non-aromatic atoms."
                )
            if "[" not in smiles and any(c in smiles for c in "cno"):
                hints.append("Example valid SMILES: CCO (ethanol), c1ccccc1 (benzene), CC(=O)O (acetic acid)")

            hint_str = "\n  ".join(hints) if hints else ""
            raise ValueError(
                f"RDKit could not parse SMILES: {smiles!r}\n  {hint_str}"
            )

        mol = Chem.AddHs(mol)

        # Generate 3-D coordinates
        result = AllChem.EmbedMolecule(mol, AllChem.ETKDGv3())
        if result == -1:
            raise ValueError(
                f"Failed to generate 3-D conformer for SMILES: {smiles!r}"
            )

        if optimize:
            try:
                AllChem.MMFFOptimizeMolecule(mol)
            except Exception:
                # MMFF may not support all molecules; fall back to UFF
                AllChem.UFFOptimizeMolecule(mol)

        conf = mol.GetConformer()
        positions = np.array(conf.GetPositions())
        symbols = [atom.GetSymbol() for atom in mol.GetAtoms()]

        atoms = Atoms(symbols=symbols, positions=positions)
        atoms.pbc = False

        # Center and add vacuum padding
        atoms.center(vacuum=vacuum)

        return Structure.from_ase_atoms(atoms)




# ---------------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------------

def fibonacci_sphere(radius: float, n_points: int) -> list[list[float]]:
    """Distribute *n_points* uniformly on a sphere of given *radius*.

    Uses the golden-angle (Fibonacci) spiral for an isotropic, uniform
    distribution — suitable for generating carbon-cage geometries.

    Parameters
    ----------
    radius
        Sphere radius in Å.
    n_points
        Number of points to place on the sphere.
    """
    points: list[list[float]] = []
    phi = np.pi * (3.0 - np.sqrt(5.0))  # golden angle

    for i in range(n_points):
        y = 1.0 - (i / (n_points - 1)) * 2.0
        r = np.sqrt(1.0 - y * y)
        theta = phi * i
        x = np.cos(theta) * r
        z = np.sin(theta) * r
        points.append([x * radius, y * radius, z * radius])

    return points


# ---------------------------------------------------------------------------
# CLI handlers
# ---------------------------------------------------------------------------

def _cmd_from_ase(args):
    """CLI handler: build a molecule from the ASE database."""
    from mmkit.io import write_atoms

    builder = ASEMoleculeBuilder()
    structure = builder.apply(name=args.name)
    output = args.output or f"mol_{args.name}.extxyz"
    path = write_atoms(output, structure.atoms)
    print(f"Built molecule {args.name!r} -> {path}  ({len(structure.atoms)} atoms)")


def _cmd_from_smiles(args):
    """CLI handler: build a molecule from a SMILES string."""
    from mmkit.io import write_atoms

    builder = SMILESMoleculeBuilder()
    kwargs = dict(smiles=args.smiles, vacuum=args.vacuum)
    if args.no_optimize:
        kwargs["optimize"] = False
    structure = builder.apply(**kwargs)

    # Derive a filename from the SMILES (first 20 chars, sanitized)
    safe_name = "".join(
        c if c.isalnum() else "_" for c in args.smiles[:20]
    )
    output = args.output or f"mol_{safe_name}.extxyz"
    path = write_atoms(output, structure.atoms)
    print(f"Built molecule from SMILES {args.smiles!r} -> {path}  "
          f"({len(structure.atoms)} atoms)")




# ---------------------------------------------------------------------------
# CLI registration
# ---------------------------------------------------------------------------

def register_cli(subparsers) -> None:
    """Register molecule subcommands with the mmkit CLI."""
    mol = subparsers.add_parser(
        "molecule",
        help="Build isolated molecules (ASE database, SMILES, organometallics, endohedral)",
    )
    mol_sub = mol.add_subparsers(dest="action", required=True)

    # -- from_ase -----------------------------------------------------------
    p_ase = mol_sub.add_parser(
        "from_ase",
        help="Build a molecule from the ASE built-in database (H2O, CO2, C60, …)",
    )
    p_ase.add_argument("name", help="Molecule name, e.g. H2O, CO2, C6H6, C60")
    p_ase.add_argument("-o", "--output", help="Output file (default: mol_<name>.extxyz)")
    p_ase.set_defaults(handler=_cmd_from_ase)

    # -- from_smiles --------------------------------------------------------
    p_smiles = mol_sub.add_parser(
        "from_smiles",
        help="Build a molecule from a SMILES string using RDKit",
    )
    p_smiles.add_argument("smiles", help="SMILES string, e.g. CCO (ethanol), c1ccccc1 (benzene)")
    p_smiles.add_argument("--vacuum", type=float, default=5.0,
                          help="Vacuum padding around molecule in Å (default: 5.0)")
    p_smiles.add_argument("--no-optimize", action="store_true",
                          help="Skip MMFF force-field optimisation")
    p_smiles.add_argument("-o", "--output", help="Output file (default: mol_<smiles>.extxyz)")
    p_smiles.set_defaults(handler=_cmd_from_smiles)

